### ISSUE TITLE
Usage of web

### ISSUE THREAD

**Issue by Alerinos** [karl-sjogren/Shorthand.ImageSharp.WebP#2]
How do I use this for imagesharp web? How can I register it?

**Comment by karl-sjogren** [comment]
You just install the nuget package to your solution with a compatible ImageSharp version and add a using for `Shorthand.ImageSharp.WebP` when you want to save an image as WebP. Then you `Image<TPixel>` objects will have an extension method called `SaveAsWebP()`.
