### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by doganince** [karl-sjogren/Shorthand.ImageSharp.WebP#3]
Hi Karl,
I added Shorthand.ImageSharp.WebP on my .net core project, its working very well on my local system with macOS. I deployed on a Linux server with a docker container, but I receiving a Broken pipeline error. 
My error has occurred on WebPEncoder.cs on stream block. All DLL files are already located in the correct location. Can you help for this problem? 

Stacktrace:
System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.IO.MemoryStream.CopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)

**Comment by karl-sjogren** [comment]
Sorry for the late reply, seems like I've muted notifications for this repo at some point..

I'm running the unit tests on Ubuntu in my CI-rigg without any problems so it should work fine on linux. What distro are you using? I'm guessing that an alpine image or similar might lack some more dependencies. Have you you installed webp in your container as described in the readme?
